# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 15 # it will paginate after this number
per_page: 15 # Repeated to fix an 'Infinity' error 
language: 'en-uk'
words_per_minute: 200

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /


# Website info
title: "Be A Voice, not an Echo"
description: "Sharing engineering knowhow"
cover: assets/images/blog-cover.jpg
logo: assets/images/blog-title-transparent.png
logo_dark: assets/images/favicon.png
favicon: assets/images/favicon.png
CNAME: #add cname for website to be created

# Social info
navigation: True # show the navbar links
subscribers: True # you need to connect an external service for this to work,
# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`
twitter: ibarrond_ # replace by your username
linkedin: albertoibarrondo # replace by your username
mail: ibarrond@eurecom.fr
github: ibarrond

# Disqus
disqus: True
disqus_shortname: ibarrond-github-io # replace with your disqus username

# Google Analytics
# google_analytics: UA-69281367-1 # replace with your GA tracking identifier

# Permalinks
permalink: /:title

algolia:
  application_id: URIHIBX1QW
  index_name:     ibarrond.github.io
  search_only_api_key: 97513f1d98c0d721051de13d1e45ba00
  extensions_to_index:
    - html
    - md
  files_to_exclude:
    - '**/index.html'
    - '**/index.md'

  settings:
    attributesToSnippet: ['*:33']
    highlightPreTag: '<em class="ais-match-highlight">'
    highlightPostTag: '</em>'

# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`

# gems and other configs
plugins_dir: [_plugins]
plugins: [jekyll-paginate, jekyll-feed]

feed:
  path: feed.xml

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: False
lsi: False
username: ibarrond
repo: ibarrond.github.io
branch: master
relative_source: ../ibarrond.github.io/
destination: ./_built_site/
url:  https://ibarrond.github.io/
production_url:  https://ibarrond.github.io/
source_url:  https://github.com/ibarrond/ibarrond.github.io/

exclude:
  - tag/**
  - assets/css
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - GHOST.txt
  - gulpfile.js
  - LICENSE
  - package.json
  - Rakefile
  - script.py
  - changelog.md
  - "*.Rmd"
  - .git*
